[package]
name = "pip-boi-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
strum = { version = "0.26.2", features = ["strum_macros"] }
strum_macros = "0.26.2"
