name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ['api', 'gui', 'gui-server']

    steps:
    - uses: actions/checkout@v4
    - name: Add Clippy
      run: "rustup component add clippy-preview"
    - name: Run Clippy
      working-directory: ${{ matrix.dir }}
      run: "cargo clippy"
